---
galaxy_info:
  author: Polaris Team
  description: Send callback notifications to orchestration service
  license: MIT
  min_ansible_version: '2.14'
  platforms: []
  galaxy_tags: []

dependencies: []
